// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibxmpkymshsqlyzffetf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlieG1wa3ltc2hzcWx5emZmZXRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk4MDMxMjcsImV4cCI6MjA5NTM3OTEyN30.7MKUpaGJgwh4QPLOsdzx4PkeTP-wZkYrgflzTNVrv6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});